/** ancilis.cli.templates.ancilis-yaml — YAML configuration template generator. */

/** Return an ancilis.yaml string for the given agent name and overlay. */
export function generateAncilisYaml(agentName: string, overlay: string): string {
  return [
    "# Ancilis configuration — generated by ancilis init",
    "# Docs: https://docs.ancilis.dev/configuration",
    "",
    "config_version: 2              # Schema version; use `ancilis config migrate` when upgrading",
    "",
    "agent:",
    `  name: ${agentName}          # Your agent's unique identifier`,
    '  description: ""              # What this agent does',
    "",
    "security:",
    "  mode: audit                  # audit = observe only, enforce = block violations",
    "",
    "compliance:",
    "  overlays:",
    `    - ${overlay}                # Compliance framework to evaluate against`,
    "",
    "# Uncomment to connect to the Ancilis platform:",
    "# cli:",
    "#   update_check: true",
    "",
  ].join("\n");
}
