/** First-value TypeScript sample scripts generated by ancilis init. */

const FRAMEWORK_LABELS: Record<string, string> = {
  langchain: "LangChain",
  openai: "OpenAI",
  anthropic: "Anthropic",
  mcp: "MCP",
  generic: "custom TypeScript",
};

function sampleScript(frameworkLabel: string): string {
  return `/**
 * First Ancilis evidence run for a ${frameworkLabel} agent.
 *
 * Run:
 *   node ancilis_scan.mjs
 *   ancilis status --config ancilis.yaml
 *   ancilis scan --config ancilis.yaml
 */
import { Engine, EvidenceStore, ToolActionProducer, loadConfig } from "ancilis";

const config = loadConfig({ path: "ancilis.yaml" });
const evidence = new EvidenceStore(config);
const engine = new Engine(config, { evidenceStore: evidence });
const producer = new ToolActionProducer(config, engine, undefined, evidence);

function searchDocs(query) {
  return { results: ["SOC 2 controls", "agent evidence", "runtime policy"] };
}

function sendReply(message) {
  return \`Sent: \${String(message)}\`;
}

const searchDocsWithAncilis = producer.wrapTool(searchDocs, undefined, "search_docs");
const sendReplyWithAncilis = producer.wrapTool(sendReply, undefined, "send_reply");

console.log(\`Agent: \${config.agentName}\`);
console.log(\`Mode: \${config.mode}\`);
console.log();

const docs = await searchDocsWithAncilis("How do we prove our agent followed policy?");
console.log("search_docs ->", docs);

const reply = await sendReplyWithAncilis("Ancilis recorded this tool call as local evidence.");
console.log("send_reply ->", reply);

const summary = await evidence.getSummary({ sessionId: producer.sessionId });
const chainStatus = summary.chainValid === false ? "BROKEN" : "intact";
console.log(\`\\nEvidence: \${String(summary.totalEvaluations ?? 0)} records this run, chain \${chainStatus}\`);
console.log("\\nNext:");
console.log("  ancilis status --config ancilis.yaml");
console.log("  ancilis scan --config ancilis.yaml");

await evidence.close();
`;
}

/** Return a runnable first-value script for the detected framework. */
export function getScanScript(framework: string): string {
  return sampleScript(FRAMEWORK_LABELS[framework] ?? FRAMEWORK_LABELS["generic"]!);
}
