"""Setup recommendation generation for Ancilis Cover."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from ancilis.mcp_server.cover.classification import classify_project
from ancilis.mcp_server.cover.models import ProjectClassification, ProjectInspection, SetupRecommendation
from ancilis.mcp_server.cover.project import inspect_project


def recommend_setup(
    *,
    root: str | Path | None = None,
    project: ProjectInspection | dict[str, Any] | None = None,
    classification: ProjectClassification | dict[str, Any] | None = None,
    project_name: str | None = None,
    language: str = "auto",
) -> SetupRecommendation:
    """Return read-only setup guidance for adding Ancilis."""
    inspected = _coerce_project(project)
    classified = _coerce_classification(classification)
    if inspected is None and root is not None:
        inspected = inspect_project(root)
    if classified is None:
        classified = classify_project(root)

    resolved_language = _resolve_language(language, inspected)
    agent_name = project_name or _project_name(root, inspected)
    install_commands = _install_commands(resolved_language)
    snippets = _integration_snippets(resolved_language)
    return SetupRecommendation(
        install_commands=install_commands,
        config_yaml=_config_yaml(agent_name, classified),
        integration_summary=_integration_summary(resolved_language, inspected),
        integration_snippets=snippets,
        validation_commands=["ancilis doctor", "ancilis scan"],
        next_steps=[
            "Create ancilis.yaml with the recommended configuration.",
            "Install Ancilis with the recommended package command.",
            "Wrap the highest-risk tool or agent entrypoint first.",
            "Run ancilis doctor and ancilis scan.",
        ],
    )


def _coerce_project(project: ProjectInspection | dict[str, Any] | None) -> ProjectInspection | None:
    if project is None:
        return None
    if isinstance(project, ProjectInspection):
        return project
    return ProjectInspection.model_validate(project)


def _coerce_classification(
    classification: ProjectClassification | dict[str, Any] | None,
) -> ProjectClassification | None:
    if classification is None:
        return None
    if isinstance(classification, ProjectClassification):
        return classification
    return ProjectClassification.model_validate(classification)


def _resolve_language(language: str, project: ProjectInspection | None) -> str:
    if language in {"python", "typescript"}:
        return language
    if project is not None and "python" in project.languages:
        return "python"
    if project is not None and "typescript" in project.languages:
        return "typescript"
    return "python"


def _project_name(root: str | Path | None, project: ProjectInspection | None) -> str:
    if project is not None:
        return Path(project.root).name or "my-agent"
    if root is not None:
        return Path(root).resolve().name or "my-agent"
    return "my-agent"


def _install_commands(language: str) -> list[str]:
    if language == "typescript":
        return ["npm install ancilis"]
    return ["pip install ancilis"]


def _config_yaml(agent_name: str, classification: ProjectClassification) -> str:
    lines = [
        "# Ancilis configuration generated by Ancilis Cover",
        "agent:",
        f"  name: {agent_name}",
        "security:",
        "  mode: audit",
        "my_agent_handles:",
    ]
    if classification.my_agent_handles:
        lines.extend(f"  - {handle}" for handle in classification.my_agent_handles)
    else:
        lines.append("  - personal_info  # review and adjust")

    lines.append("compliance:")
    lines.append("  overlays:")
    if classification.active_overlays:
        lines.extend(f"    - {overlay}" for overlay in classification.active_overlays)
    else:
        lines.append("    - soc2  # review and adjust")
    return "\n".join(lines) + "\n"


def _integration_summary(
    language: str,
    project: ProjectInspection | None,
) -> str:
    producers = project.recommended_producers if project is not None else []
    if producers:
        return f"Start with the {producers[0]} producer for this {language} project."
    return f"Start by wrapping the highest-risk tool call in this {language} project."


def _integration_snippets(language: str) -> dict[str, str]:
    python = "\n".join(
        [
            "from ancilis import ToolActionProducer, load_config",
            "from ancilis.engine import Engine",
            "",
            "config = load_config()",
            "engine = Engine(config)",
            "producer = ToolActionProducer(config=config, engine=engine)",
            "safe_tool = producer.wrap_tool(existing_tool, tool_name=\"existing_tool\")",
        ]
    )
    typescript = "\n".join(
        [
            "import { loadConfig, Engine, ToolActionProducer } from 'ancilis';",
            "",
            "const config = loadConfig();",
            "const engine = new Engine(config);",
            "const producer = new ToolActionProducer(config, engine);",
            "const safeTool = producer.wrapTool(existingTool, config.agentName, 'existing_tool');",
        ]
    )
    if language == "typescript":
        return {"typescript": typescript, "python": python}
    return {"python": python, "typescript": typescript}
