import { describe, it, expect, vi, beforeAll, afterAll } from "vitest";
import { writeFileSync, mkdirSync, rmSync, existsSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { randomUUID } from "node:crypto";

import { ManifestDetector } from "../src/ancilis/deps/manifest.js";
import { OSVClient } from "../src/ancilis/deps/osv.js";
import { DependencyScanner } from "../src/ancilis/deps/scanner.js";
import type { Dependency } from "../src/ancilis/deps/types.js";

// ---------------------------------------------------------------------------
// Test fixtures directory
// ---------------------------------------------------------------------------

let TMP_DIR: string;

beforeAll(() => {
  TMP_DIR = join(tmpdir(), `ancilis-deps-test-${randomUUID()}`);
  mkdirSync(TMP_DIR, { recursive: true });
});

afterAll(() => {
  if (existsSync(TMP_DIR)) {
    rmSync(TMP_DIR, { recursive: true, force: true });
  }
});

function writeFixture(dir: string, filename: string, content: string): string {
  const path = join(dir, filename);
  writeFileSync(path, content, "utf-8");
  return path;
}

// ---------------------------------------------------------------------------
// ManifestDetector — package-lock.json (v2)
// ---------------------------------------------------------------------------

describe("ManifestDetector — package-lock.json v2", () => {
  it("parses packages from lockfileVersion 2 format", () => {
    const dir = join(TMP_DIR, "pkglock-v2");
    mkdirSync(dir, { recursive: true });
    writeFixture(dir, "package-lock.json", JSON.stringify({
      lockfileVersion: 2,
      packages: {
        "": { name: "myapp", version: "1.0.0" },
        "node_modules/lodash": { version: "4.17.21" },
        "node_modules/express": { version: "4.18.2" },
        "node_modules/@babel/core": { version: "7.22.0" },
      },
    }));

    const detector = new ManifestDetector();
    const manifests = detector.detect(dir);
    expect(manifests).toHaveLength(1);
    const deps = manifests[0]!.dependencies;
    expect(deps.find((d) => d.name === "lodash")?.version).toBe("4.17.21");
    expect(deps.find((d) => d.name === "express")?.version).toBe("4.18.2");
    expect(deps.find((d) => d.name === "@babel/core")?.version).toBe("7.22.0");
    // Root entry ("") should be skipped
    expect(deps.find((d) => d.name === "")).toBeUndefined();
  });

  it("parses packages from lockfileVersion 1 format", () => {
    const dir = join(TMP_DIR, "pkglock-v1");
    mkdirSync(dir, { recursive: true });
    writeFixture(dir, "package-lock.json", JSON.stringify({
      lockfileVersion: 1,
      dependencies: {
        lodash: { version: "4.17.21" },
        chalk: { version: "5.3.0" },
      },
    }));

    const detector = new ManifestDetector();
    const manifests = detector.detect(dir);
    const deps = manifests[0]!.dependencies;
    expect(deps).toHaveLength(2);
    expect(deps.find((d) => d.name === "lodash")?.version).toBe("4.17.21");
  });

  it("skips entries without a version field", () => {
    const dir = join(TMP_DIR, "pkglock-noversion");
    mkdirSync(dir, { recursive: true });
    writeFixture(dir, "package-lock.json", JSON.stringify({
      lockfileVersion: 2,
      packages: {
        "node_modules/lodash": { version: "4.17.21" },
        "node_modules/missing": {},
      },
    }));

    const detector = new ManifestDetector();
    const deps = detector.detect(dir)[0]!.dependencies;
    expect(deps).toHaveLength(1);
    expect(deps[0]!.name).toBe("lodash");
  });

  it("returns empty array for invalid JSON", () => {
    const dir = join(TMP_DIR, "pkglock-bad");
    mkdirSync(dir, { recursive: true });
    writeFixture(dir, "package-lock.json", "not json {");
    const detector = new ManifestDetector();
    const deps = detector.detect(dir)[0]!.dependencies;
    expect(deps).toHaveLength(0);
  });
});

// ---------------------------------------------------------------------------
// ManifestDetector — yarn.lock
// ---------------------------------------------------------------------------

describe("ManifestDetector — yarn.lock", () => {
  it("parses simple yarn v1 lockfile", () => {
    const dir = join(TMP_DIR, "yarn-v1");
    mkdirSync(dir, { recursive: true });
    writeFixture(dir, "yarn.lock", `# THIS IS AN AUTOGENERATED FILE.
# yarn lockfile v1

lodash@^4.17.0:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
  integrity sha512-abc

express@^4.18.0:
  version "4.18.2"
  resolved "https://registry.yarnpkg.com/express/-/express-4.18.2.tgz"
`);

    const detector = new ManifestDetector();
    const manifests = detector.detect(dir);
    expect(manifests).toHaveLength(1);
    const deps = manifests[0]!.dependencies;
    expect(deps.find((d) => d.name === "lodash")?.version).toBe("4.17.21");
    expect(deps.find((d) => d.name === "express")?.version).toBe("4.18.2");
  });

  it("deduplicates multiple specifiers for same package", () => {
    const dir = join(TMP_DIR, "yarn-dedup");
    mkdirSync(dir, { recursive: true });
    writeFixture(dir, "yarn.lock", `"lodash@^4.0.0", "lodash@^4.17.0":
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
`);
    const detector = new ManifestDetector();
    const deps = detector.detect(dir)[0]!.dependencies;
    const lodashEntries = deps.filter((d) => d.name === "lodash");
    expect(lodashEntries).toHaveLength(1);
    expect(lodashEntries[0]!.version).toBe("4.17.21");
  });

  it("parses scoped packages in yarn.lock", () => {
    const dir = join(TMP_DIR, "yarn-scoped");
    mkdirSync(dir, { recursive: true });
    writeFixture(dir, "yarn.lock", `"@babel/core@^7.0.0":
  version "7.22.0"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.22.0.tgz"
`);
    const detector = new ManifestDetector();
    const deps = detector.detect(dir)[0]!.dependencies;
    expect(deps.find((d) => d.name === "@babel/core")?.version).toBe("7.22.0");
  });
});

// ---------------------------------------------------------------------------
// ManifestDetector — pnpm-lock.yaml
// ---------------------------------------------------------------------------

describe("ManifestDetector — pnpm-lock.yaml", () => {
  it("parses pnpm v6 format (no leading slash)", () => {
    const dir = join(TMP_DIR, "pnpm-v6");
    mkdirSync(dir, { recursive: true });
    writeFixture(dir, "pnpm-lock.yaml", `lockfileVersion: '6.0'
packages:
  lodash@4.17.21:
    resolution: {integrity: sha512-abc}
    dev: false
  express@4.18.2:
    resolution: {integrity: sha512-def}
`);
    const detector = new ManifestDetector();
    const manifests = detector.detect(dir);
    const deps = manifests[0]!.dependencies;
    expect(deps.find((d) => d.name === "lodash")?.version).toBe("4.17.21");
    expect(deps.find((d) => d.name === "express")?.version).toBe("4.18.2");
  });

  it("parses pnpm v5 format (leading slash)", () => {
    const dir = join(TMP_DIR, "pnpm-v5");
    mkdirSync(dir, { recursive: true });
    writeFixture(dir, "pnpm-lock.yaml", `lockfileVersion: 5.4
packages:
  /lodash@4.17.21:
    resolution: {integrity: sha512-abc}
  /@babel/core@7.22.0:
    resolution: {integrity: sha512-def}
`);
    const detector = new ManifestDetector();
    const deps = detector.detect(dir)[0]!.dependencies;
    expect(deps.find((d) => d.name === "lodash")?.version).toBe("4.17.21");
    expect(deps.find((d) => d.name === "@babel/core")?.version).toBe("7.22.0");
  });
});

// ---------------------------------------------------------------------------
// ManifestDetector — package.json fallback
// ---------------------------------------------------------------------------

describe("ManifestDetector — package.json fallback", () => {
  it("extracts pinned versions from dependencies", () => {
    const dir = join(TMP_DIR, "pkgjson-pinned");
    mkdirSync(dir, { recursive: true });
    writeFixture(dir, "package.json", JSON.stringify({
      name: "myapp",
      version: "1.0.0",
      dependencies: {
        lodash: "4.17.21",
        express: "^4.18.0",
        chalk: "~5.3.0",
      },
      devDependencies: {
        vitest: "4.1.2",
      },
    }));
    const detector = new ManifestDetector();
    const deps = detector.detect(dir)[0]!.dependencies;
    // Only pinned (starting with digit)
    expect(deps.find((d) => d.name === "lodash")?.version).toBe("4.17.21");
    expect(deps.find((d) => d.name === "vitest")?.version).toBe("4.1.2");
    // Semver ranges should be skipped
    expect(deps.find((d) => d.name === "express")).toBeUndefined();
    expect(deps.find((d) => d.name === "chalk")).toBeUndefined();
  });
});

// ---------------------------------------------------------------------------
// ManifestDetector — empty directory
// ---------------------------------------------------------------------------

describe("ManifestDetector — empty directory", () => {
  it("returns empty array when no manifests present", () => {
    const dir = join(TMP_DIR, "empty");
    mkdirSync(dir, { recursive: true });
    const detector = new ManifestDetector();
    const manifests = detector.detect(dir);
    expect(manifests).toHaveLength(0);
  });
});

// ---------------------------------------------------------------------------
// OSVClient
// ---------------------------------------------------------------------------

describe("OSVClient", () => {
  it("returns empty map when all deps lack versions", async () => {
    const client = new OSVClient();
    const deps: Dependency[] = [{ name: "lodash", version: null, sourceFile: "package.json" }];
    const result = await client.queryBatch(deps);
    expect(result).toEqual({});
    expect(client.lastError).toBeNull();
  });

  it("sets lastError on network failure", async () => {
    // Mock fetch to throw
    const origFetch = global.fetch;
    global.fetch = vi.fn().mockRejectedValue(new Error("network failure")) as typeof fetch;
    try {
      const client = new OSVClient();
      const deps: Dependency[] = [{ name: "lodash", version: "4.17.21", sourceFile: "p.json" }];
      const result = await client.queryBatch(deps);
      expect(result).toEqual({});
      expect(client.lastError).toMatch(/network failure/i);
    } finally {
      global.fetch = origFetch;
    }
  });

  it("sets lastError on non-OK HTTP response", async () => {
    const origFetch = global.fetch;
    global.fetch = vi.fn().mockResolvedValue({
      ok: false,
      status: 500,
      json: async () => ({}),
    }) as unknown as typeof fetch;
    try {
      const client = new OSVClient();
      const deps: Dependency[] = [{ name: "lodash", version: "4.17.21", sourceFile: "p.json" }];
      const result = await client.queryBatch(deps);
      expect(result).toEqual({});
      expect(client.lastError).toMatch(/500/);
    } finally {
      global.fetch = origFetch;
    }
  });

  it("maps OSV response to Vuln objects", async () => {
    const osvResponse = {
      results: [
        {
          vulns: [
            {
              id: "GHSA-xxxx-1234",
              summary: "Prototype pollution in lodash",
              severity: [{ type: "CVSS_V3", score: "9.8" }],
              aliases: ["CVE-2021-1234"],
              affected: [
                {
                  package: { name: "lodash", ecosystem: "npm" },
                  ranges: [
                    { events: [{ introduced: "0" }, { fixed: "4.17.21" }] },
                  ],
                },
              ],
            },
          ],
        },
      ],
    };

    const origFetch = global.fetch;
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: async () => osvResponse,
    }) as unknown as typeof fetch;

    try {
      const client = new OSVClient();
      const deps: Dependency[] = [{ name: "lodash", version: "4.17.20", sourceFile: "p.json" }];
      const result = await client.queryBatch(deps);

      expect(Object.keys(result)).toContain("lodash");
      const vulns = result["lodash"]!;
      expect(vulns).toHaveLength(1);
      expect(vulns[0]!.id).toBe("GHSA-xxxx-1234");
      expect(vulns[0]!.severity).toBe("CRITICAL");
      expect(vulns[0]!.fixedVersion).toBe("4.17.21");
      expect(vulns[0]!.aliases).toContain("CVE-2021-1234");
    } finally {
      global.fetch = origFetch;
    }
  });

  it("returns empty map for no vulnerabilities", async () => {
    const origFetch = global.fetch;
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: async () => ({ results: [{}] }),
    }) as unknown as typeof fetch;

    try {
      const client = new OSVClient();
      const deps: Dependency[] = [{ name: "lodash", version: "4.17.21", sourceFile: "p.json" }];
      const result = await client.queryBatch(deps);
      expect(result).toEqual({});
      expect(client.lastError).toBeNull();
    } finally {
      global.fetch = origFetch;
    }
  });

  it("maps CVSS HIGH score to HIGH severity", async () => {
    const osvResponse = {
      results: [
        {
          vulns: [
            {
              id: "GHSA-high",
              summary: "High severity issue",
              severity: [{ type: "CVSS_V3", score: "7.5" }],
              aliases: [],
              affected: [],
            },
          ],
        },
      ],
    };
    const origFetch = global.fetch;
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: async () => osvResponse,
    }) as unknown as typeof fetch;

    try {
      const client = new OSVClient();
      const deps: Dependency[] = [{ name: "pkg", version: "1.0.0", sourceFile: "p.json" }];
      const result = await client.queryBatch(deps);
      expect(result["pkg"]![0]!.severity).toBe("HIGH");
    } finally {
      global.fetch = origFetch;
    }
  });

  it("falls back to database_specific severity", async () => {
    const osvResponse = {
      results: [
        {
          vulns: [
            {
              id: "GHSA-medium",
              summary: "Medium severity issue",
              severity: [],
              database_specific: { severity: "MEDIUM" },
              aliases: [],
              affected: [],
            },
          ],
        },
      ],
    };
    const origFetch = global.fetch;
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: async () => osvResponse,
    }) as unknown as typeof fetch;

    try {
      const client = new OSVClient();
      const deps: Dependency[] = [{ name: "pkg", version: "1.0.0", sourceFile: "p.json" }];
      const result = await client.queryBatch(deps);
      expect(result["pkg"]![0]!.severity).toBe("MEDIUM");
    } finally {
      global.fetch = origFetch;
    }
  });
});

// ---------------------------------------------------------------------------
// DependencyScanner
// ---------------------------------------------------------------------------

function makeConfig(mode: "audit" | "enforce" = "audit", de01Enabled = true) {
  return {
    agentName: "test-agent",
    agentOwner: "",
    mode,
    controls: new Map([["DE-01", { enabled: de01Enabled, controlId: "DE-01", controlName: "Dependency Evaluation", reason: "" }]]),
    dataClassifications: new Map(),
    activeOverlays: new Map(),
    unavailableOverlays: [],
    overlayAdjustments: [],
    evidenceRetentionDays: 30,
    humanOversightRequired: false,
    warnings: [],
    toolsAllowed: [],
    toolsBlocked: [],
    scopeMaxActionsPerMinute: null,
    scopeAllowedDestinations: [],
    scopeBlockedDestinations: [],
    activeCertifications: [],
  };
}

describe("DependencyScanner", () => {
  it("returns empty array when DE-01 is disabled", async () => {
    const scanner = new DependencyScanner(makeConfig("audit", false));
    const results = await scanner.scan(TMP_DIR);
    expect(results).toHaveLength(0);
  });

  it("returns SKIP result when no manifests found", async () => {
    const dir = join(TMP_DIR, "scan-empty");
    mkdirSync(dir, { recursive: true });
    const scanner = new DependencyScanner(makeConfig());
    const results = await scanner.scan(dir);
    expect(results).toHaveLength(1);
    expect(results[0]!.controlResults[0]!.result).toBe("SKIP");
  });

  it("returns FLAG when OSV.dev fails", async () => {
    const dir = join(TMP_DIR, "scan-oserror");
    mkdirSync(dir, { recursive: true });
    writeFixture(dir, "package-lock.json", JSON.stringify({
      lockfileVersion: 2,
      packages: {
        "node_modules/lodash": { version: "4.17.21" },
      },
    }));

    const origFetch = global.fetch;
    global.fetch = vi.fn().mockRejectedValue(new Error("fetch error")) as typeof fetch;
    try {
      const scanner = new DependencyScanner(makeConfig());
      const results = await scanner.scan(dir);
      expect(results[0]!.controlResults[0]!.result).toBe("FLAG");
      expect(results[0]!.controlResults[0]!.detail).toMatch(/fetch error/i);
    } finally {
      global.fetch = origFetch;
    }
  });

  it("returns PASS when no vulnerabilities found", async () => {
    const dir = join(TMP_DIR, "scan-pass");
    mkdirSync(dir, { recursive: true });
    writeFixture(dir, "package-lock.json", JSON.stringify({
      lockfileVersion: 2,
      packages: {
        "node_modules/lodash": { version: "4.17.21" },
      },
    }));

    const origFetch = global.fetch;
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: async () => ({ results: [{}] }),
    }) as unknown as typeof fetch;
    try {
      const scanner = new DependencyScanner(makeConfig());
      const results = await scanner.scan(dir);
      expect(results[0]!.controlResults[0]!.result).toBe("PASS");
      expect(results[0]!.decision).toBe("ALLOW");
    } finally {
      global.fetch = origFetch;
    }
  });

  it("returns FAIL and BLOCK decision for CRITICAL vulnerability", async () => {
    const dir = join(TMP_DIR, "scan-critical");
    mkdirSync(dir, { recursive: true });
    writeFixture(dir, "package-lock.json", JSON.stringify({
      lockfileVersion: 2,
      packages: {
        "node_modules/lodash": { version: "4.17.20" },
      },
    }));

    const osvResponse = {
      results: [
        {
          vulns: [
            {
              id: "GHSA-crit-1",
              summary: "Critical RCE",
              severity: [{ type: "CVSS_V3", score: "9.8" }],
              aliases: [],
              affected: [
                {
                  package: { name: "lodash", ecosystem: "npm" },
                  ranges: [{ events: [{ introduced: "0" }, { fixed: "4.17.21" }] }],
                },
              ],
            },
          ],
        },
      ],
    };

    const origFetch = global.fetch;
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: async () => osvResponse,
    }) as unknown as typeof fetch;
    try {
      const scanner = new DependencyScanner(makeConfig());
      const results = await scanner.scan(dir);
      expect(results[0]!.decision).toBe("BLOCK");
      const cr = results[0]!.controlResults[0]!;
      expect(cr.result).toBe("FAIL");
      expect(cr.remediationHint).toMatch(/4\.17\.21/);
      expect(cr.evidenceData["package"]).toBe("lodash");
      expect(cr.evidenceData["severity"]).toBe("CRITICAL");
    } finally {
      global.fetch = origFetch;
    }
  });

  it("returns FLAG and FLAG decision for MEDIUM vulnerability", async () => {
    const dir = join(TMP_DIR, "scan-medium");
    mkdirSync(dir, { recursive: true });
    writeFixture(dir, "package-lock.json", JSON.stringify({
      lockfileVersion: 2,
      packages: {
        "node_modules/express": { version: "4.18.1" },
      },
    }));

    const osvResponse = {
      results: [
        {
          vulns: [
            {
              id: "GHSA-med-1",
              summary: "Open redirect",
              severity: [{ type: "CVSS_V3", score: "5.3" }],
              aliases: [],
              affected: [],
            },
          ],
        },
      ],
    };

    const origFetch = global.fetch;
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: async () => osvResponse,
    }) as unknown as typeof fetch;
    try {
      const scanner = new DependencyScanner(makeConfig());
      const results = await scanner.scan(dir);
      expect(results[0]!.decision).toBe("FLAG");
      expect(results[0]!.controlResults[0]!.result).toBe("FLAG");
    } finally {
      global.fetch = origFetch;
    }
  });

  it("EvaluationResult has required fields", async () => {
    const dir = join(TMP_DIR, "scan-fields");
    mkdirSync(dir, { recursive: true });
    writeFixture(dir, "package-lock.json", JSON.stringify({
      lockfileVersion: 2,
      packages: {
        "node_modules/pkg": { version: "1.0.0" },
      },
    }));

    const origFetch = global.fetch;
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: async () => ({ results: [{}] }),
    }) as unknown as typeof fetch;
    try {
      const scanner = new DependencyScanner(makeConfig());
      const results = await scanner.scan(dir);
      const r = results[0]!;
      expect(r.evaluationId).toBeTruthy();
      expect(r.actionId).toMatch(/^dep-scan-/);
      expect(r.timestamp).toBeTruthy();
      expect(r.agentId).toBe("cli-scan");
      expect(r.sourceType).toBe("dependency_scan");
      expect(r.mode).toBe("audit");
    } finally {
      global.fetch = origFetch;
    }
  });

  it("sorts packages worst-first in controlResults", async () => {
    const dir = join(TMP_DIR, "scan-sort");
    mkdirSync(dir, { recursive: true });
    writeFixture(dir, "package-lock.json", JSON.stringify({
      lockfileVersion: 2,
      packages: {
        "node_modules/aaa": { version: "1.0.0" },
        "node_modules/bbb": { version: "1.0.0" },
      },
    }));

    // aaa has MEDIUM, bbb has CRITICAL
    const osvResponse = {
      results: [
        {
          vulns: [{ id: "MED-1", summary: "Medium", severity: [{ type: "CVSS_V3", score: "5.0" }], aliases: [], affected: [] }],
        },
        {
          vulns: [{ id: "CRIT-1", summary: "Critical", severity: [{ type: "CVSS_V3", score: "9.9" }], aliases: [], affected: [] }],
        },
      ],
    };

    const origFetch = global.fetch;
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: async () => osvResponse,
    }) as unknown as typeof fetch;
    try {
      const scanner = new DependencyScanner(makeConfig());
      const results = await scanner.scan(dir);
      const crs = results[0]!.controlResults;
      // bbb (CRITICAL) should appear before aaa (MEDIUM)
      expect(crs[0]!.evidenceData["package"]).toBe("bbb");
      expect(crs[1]!.evidenceData["package"]).toBe("aaa");
    } finally {
      global.fetch = origFetch;
    }
  });

  it("respects enforce mode in EvaluationResult", async () => {
    const dir = join(TMP_DIR, "scan-enforce");
    mkdirSync(dir, { recursive: true });
    writeFixture(dir, "package-lock.json", JSON.stringify({
      lockfileVersion: 2,
      packages: { "node_modules/pkg": { version: "1.0.0" } },
    }));

    const origFetch = global.fetch;
    global.fetch = vi.fn().mockResolvedValue({
      ok: true,
      json: async () => ({ results: [{}] }),
    }) as unknown as typeof fetch;
    try {
      const scanner = new DependencyScanner(makeConfig("enforce"));
      const results = await scanner.scan(dir);
      expect(results[0]!.mode).toBe("enforce");
    } finally {
      global.fetch = origFetch;
    }
  });
});
