"""Output format rendering — terminal, markdown, PDF."""

from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path
from typing import Any

from ancilis.report.generator import ReportData


def render_terminal(data: ReportData) -> str:
    """Render report data as terminal output."""
    lines: list[str] = []

    # Header
    lines.append(f"Ancilis Posture Report — {data.agent_name}")
    lines.append(f"Period: {_short_date(data.period_start)} to {_short_date(data.period_end)}")
    lines.append(f"Mode: {data.mode}")
    lines.append("")

    # Baseline section
    _render_baseline_terminal(lines, data.baseline)

    # Compliance sections
    for section in data.compliance_sections:
        lines.append("")
        _render_compliance_terminal(lines, section)

    # Certification section
    if data.certification:
        lines.append("")
        _render_certification_terminal(lines, data.certification)

    # Evidence integrity
    lines.append("")
    chain_status = "\u2713 intact" if data.chain_valid else "\u2717 BROKEN"
    lines.append(f"Evidence: {data.total_evaluations:,} records, hash chain {chain_status}")

    return "\n".join(lines)


def render_markdown(data: ReportData) -> str:
    """Render report data as markdown."""
    lines: list[str] = []

    is_aiuc1 = data.report_format == "aiuc1-readiness"

    if is_aiuc1 and data.certification:
        _render_aiuc1_readiness_markdown(lines, data)
        return "\n".join(lines)

    # Standard report
    lines.append(f"# Ancilis Posture Report — {data.agent_name}")
    lines.append("")
    lines.append(f"**Period:** {_short_date(data.period_start)} to {_short_date(data.period_end)}  ")
    lines.append(f"**Generated:** {_short_date(data.generated_at)}  ")
    lines.append(f"**Mode:** {data.mode}")
    lines.append("")

    # Baseline
    _render_baseline_markdown(lines, data.baseline)

    # Compliance
    for section in data.compliance_sections:
        lines.append("")
        _render_compliance_markdown(lines, section)

    # Certification
    if data.certification:
        lines.append("")
        _render_certification_markdown(lines, data.certification)

    # Evidence
    lines.append("")
    lines.append("## Evidence Integrity")
    lines.append("")
    chain = "intact (verified)" if data.chain_valid else "**BROKEN**"
    lines.append(f"- Evidence records: {data.total_evaluations:,}")
    lines.append(f"- Hash chain: {chain}")
    lines.append("")
    lines.append("---")
    lines.append("*Generated by Ancilis SDK v0.1*")

    return "\n".join(lines)


def render_pdf(markdown: str, output_path: str) -> None:
    """Convert markdown to PDF using pandoc."""
    with tempfile.NamedTemporaryFile(mode="w", suffix=".md", delete=False) as f:
        f.write(markdown)
        md_path = f.name

    try:
        subprocess.run(
            ["pandoc", md_path, "-o", output_path, "--pdf-engine=xelatex"],
            check=True,
            capture_output=True,
        )
    except FileNotFoundError:
        # pandoc not installed — write markdown instead
        Path(output_path).write_text(markdown)
    except subprocess.CalledProcessError:
        # pandoc failed — write markdown as fallback
        Path(output_path).write_text(markdown)
    finally:
        Path(md_path).unlink(missing_ok=True)


# --- Terminal section renderers ---


def _render_baseline_terminal(lines: list[str], baseline: dict[str, Any]) -> None:
    total = baseline.get("total_evaluations", 0)
    decisions = baseline.get("decisions", {})
    lines.append(f"Evaluations: {total:,} total, {decisions.get('block', 0)} blocked")
    lines.append("")
    lines.append("Controls:")
    for c in baseline.get("controls", []):
        if c["total"] > 0:
            mark = "\u2713" if c["failed"] == 0 else "\u2717"
            lines.append(f"  {mark} {c['display_name']} — {c['pass_rate']}% pass rate ({c['total']} evaluations)")
        else:
            lines.append(f"  - {c['display_name']} — no evaluations recorded")

    tools = baseline.get("tools_evaluated", [])
    if tools:
        lines.append("")
        lines.append(f"Tools evaluated: {', '.join(tools)}")


def _render_compliance_terminal(lines: list[str], section: dict[str, Any]) -> None:
    name = section["overlay_name"]
    trigger = section.get("triggered_by", "")
    lines.append(f"{name} Compliance Posture")
    if trigger:
        lines.append(f"Activated by: {trigger} declaration")
    strict = section.get("strict_controls", [])
    if strict:
        lines.append(f"Controls at strict threshold: {', '.join(strict)}")
    lines.append("")

    for c in section.get("controls", []):
        citations = ", ".join(c.get("citations", []))
        if c["total"] > 0:
            mark = "\u2713" if c["failed"] == 0 else "\u2717"
            lines.append(f"  {citations}  {mark} {c['control_id']}: {c['total']} evaluations, {c['pass_rate']}% pass")
        else:
            lines.append(f"  {citations}  - {c['control_id']}: no evaluations")

    retention = section.get("evidence_retention_days", 365)
    met = "\u2713" if section.get("retention_met", True) else "\u2717"
    lines.append(f"  Evidence retention: {retention} days {met}")

    gaps = section.get("gaps", [])
    if gaps:
        lines.append("")
        lines.append("  Areas for improvement:")
        for g in gaps:
            lines.append(f"    - {g['display_name']}: {g['failed']} issues in reporting period")


def _render_certification_terminal(lines: list[str], cert: dict[str, Any]) -> None:
    lines.append(f"{cert['certification_name']} Readiness")
    readiness = cert.get("readiness_percentage", 0)
    coverage = cert.get("coverage_percentage", 0)
    ready = cert.get("ready_count", 0)
    lines.append(f"  Readiness: {readiness}% ({ready} of {cert['total_requirements']} requirements passing)")
    lines.append(f"  Coverage: {coverage}% ({cert['automated_count']} automated, {cert['operator_count']} operator)")
    chain = "intact" if cert.get("chain_valid", True) else "BROKEN"
    lines.append(f"  Evidence records: {cert.get('evidence_count', 0):,}, hash chain {chain}")


# --- Markdown section renderers ---


def _render_baseline_markdown(lines: list[str], baseline: dict[str, Any]) -> None:
    lines.append("## Baseline Security")
    lines.append("")
    total = baseline.get("total_evaluations", 0)
    decisions = baseline.get("decisions", {})
    lines.append(f"- Evaluations: {total:,}")
    lines.append(f"- Blocked: {decisions.get('block', 0)}")
    lines.append("")
    lines.append("| Control | Pass Rate | Evaluations | Status |")
    lines.append("|---------|-----------|-------------|--------|")
    for c in baseline.get("controls", []):
        if c["total"] > 0:
            status = "Pass" if c["failed"] == 0 else f"{c['failed']} failures"
            lines.append(f"| {c['display_name']} | {c['pass_rate']}% | {c['total']} | {status} |")
        else:
            lines.append(f"| {c['display_name']} | - | 0 | No data |")

    tools = baseline.get("tools_evaluated", [])
    if tools:
        lines.append("")
        lines.append(f"**Tools evaluated:** {', '.join(tools)}")


def _render_compliance_markdown(lines: list[str], section: dict[str, Any]) -> None:
    name = section["overlay_name"]
    lines.append(f"## {name} Compliance Posture")
    lines.append("")
    trigger = section.get("triggered_by", "")
    if trigger:
        lines.append(f"**Activated by:** {trigger} declaration  ")
    strict = section.get("strict_controls", [])
    if strict:
        lines.append(f"**Controls at strict threshold:** {', '.join(strict)}  ")
    lines.append("")

    lines.append("| Citation | Control | Evaluations | Pass Rate |")
    lines.append("|----------|---------|-------------|-----------|")
    for c in section.get("controls", []):
        citations = ", ".join(c.get("citations", []))
        if c["total"] > 0:
            lines.append(f"| {citations} | {c['control_id']} | {c['total']} | {c['pass_rate']}% |")
        else:
            lines.append(f"| {citations} | {c['control_id']} | 0 | - |")

    retention = section.get("evidence_retention_days", 365)
    met = "\u2713" if section.get("retention_met", True) else "\u2717"
    lines.append("")
    lines.append(f"Evidence retention: {retention} days {met}")

    gaps = section.get("gaps", [])
    if gaps:
        lines.append("")
        lines.append("### Areas for Improvement")
        lines.append("")
        for g in gaps:
            lines.append(f"- **{g['display_name']}**: {g['failed']} issues in reporting period")


def _render_certification_markdown(lines: list[str], cert: dict[str, Any]) -> None:
    lines.append("## AIUC-1 Certification Readiness")
    lines.append("")
    readiness = cert.get("readiness_percentage", 0)
    ready = cert.get("ready_count", 0)
    coverage = cert.get("coverage_percentage", 0)
    lines.append(f"- Readiness: {readiness}% ({ready} of {cert['total_requirements']} requirements passing)")
    lines.append(f"- Coverage: {coverage}% ({cert['automated_count']} automated, {cert['operator_count']} operator)")
    chain = "intact (verified)" if cert.get("chain_valid", True) else "**BROKEN**"
    lines.append(f"- Evidence records: {cert.get('evidence_count', 0):,}")
    lines.append(f"- Hash chain: {chain}")

    # Automated coverage
    lines.append("")
    lines.append("### Automated Coverage")
    lines.append("")
    lines.append("| Requirement | AKSI Control | Evidence |")
    lines.append("|-------------|-------------|----------|")
    for item in cert.get("automated_coverage", []):
        count = item.get("evidence_count", 0)
        status = f"{count} records" if count > 0 else "No data"
        lines.append(f"| {item['requirement_id']} | {item['aksi_control']} | {status} |")

    # Operator actions
    operator = cert.get("operator_action_required", [])
    if operator:
        lines.append("")
        lines.append("### Operator Action Required")
        lines.append("")
        lines.append("These items require governance documentation from your team.")
        lines.append("Ancilis generates the evidence these documents cite.")
        lines.append("")
        for item in operator:
            lines.append(f"- **{item['requirement_id']}**: {item['description']}")


def _render_aiuc1_readiness_markdown(lines: list[str], data: ReportData) -> None:
    """Render the AIUC-1 specific readiness report."""
    cert = data.certification
    if not cert:
        return

    lines.append("# AIUC-1 READINESS REPORT")
    lines.append("")
    lines.append(f"**Agent:** {data.agent_name}  ")
    lines.append(f"**Period:** {_short_date(data.period_start)} to {_short_date(data.period_end)}  ")
    lines.append(f"**Generated:** {_short_date(data.generated_at)}")
    lines.append("")

    # Coverage summary
    lines.append("## Readiness Summary")
    lines.append("")
    readiness = cert.get("readiness_percentage", 0)
    ready = cert.get("ready_count", 0)
    coverage = cert.get("coverage_percentage", 0)
    lines.append(f"- Readiness: {readiness}% ({ready} of {cert['total_requirements']} requirements passing)")
    lines.append(f"- Coverage: {coverage}% ({cert['automated_count']} automated, {cert['operator_count']} operator)")
    lines.append(f"- Evidence records: {cert.get('evidence_count', 0):,} over reporting period")
    chain = "intact (verified)" if cert.get("chain_valid", True) else "**BROKEN**"
    lines.append(f"- Hash chain: {chain}")

    # Automated coverage
    lines.append("")
    lines.append("## Automated Coverage")
    lines.append("")
    lines.append("| Requirement | AKSI Control | Evidence |")
    lines.append("|-------------|-------------|----------|")
    for item in cert.get("automated_coverage", []):
        count = item.get("evidence_count", 0)
        passed = item.get("passed", 0)
        failed = item.get("failed", 0)
        flagged = item.get("flagged", 0)
        detail_parts: list[str] = []
        if count > 0:
            detail_parts.append(f"{count} records")
            if failed > 0:
                detail_parts.append(f"{failed} failures")
            if flagged > 0:
                detail_parts.append(f"{flagged} flags")
        else:
            detail_parts.append("No data")
        lines.append(f"| {item['requirement_id']} | {item['aksi_control']} | {', '.join(detail_parts)} |")

    # Operator actions
    operator = cert.get("operator_action_required", [])
    if operator:
        lines.append("")
        lines.append("## Operator Action Required")
        lines.append("")
        lines.append("These items require governance documentation from your team.")
        lines.append("Ancilis generates the evidence these documents cite.")
        lines.append("")
        for item in operator:
            lines.append(f"**{item['requirement_id']}** — {item['description']}")
            lines.append("")

    # Compliance sections if overlays active
    for section in data.compliance_sections:
        lines.append("")
        _render_compliance_markdown(lines, section)

    # Advisory
    if data.advisory:
        lines.append("")
        lines.append("## Classification Advisory")
        lines.append("")
        # advisory rendering would go here

    lines.append("")
    lines.append("---")
    lines.append("*Generated by Ancilis SDK v0.1*")


def _short_date(iso: str) -> str:
    """Extract date portion from ISO timestamp."""
    if "T" in iso:
        return iso.split("T")[0]
    return iso[:10] if len(iso) >= 10 else iso
