"""Ancilis YAML configuration template generator."""

from __future__ import annotations


def generate_ancilis_yaml(agent_name: str, overlay: str) -> str:
    """Return an ancilis.yaml string for the given agent name and overlay."""
    return (
        "# Ancilis configuration — generated by ancilis init\n"
        "# Docs: https://docs.ancilis.dev/configuration\n"
        "\n"
        "agent:\n"
        f"  name: {agent_name}          # Your agent's unique identifier\n"
        '  description: ""              # What this agent does\n'
        "\n"
        "security:\n"
        "  mode: audit                  # audit = observe only, enforce = block violations\n"
        "\n"
        "compliance:\n"
        "  overlays:\n"
        f"    - {overlay}                # Compliance framework to evaluate against\n"
        "\n"
        "# Uncomment to connect to the Ancilis platform:\n"
        "# cli:\n"
        "#   update_check: true\n"
    )
