"""Ancilis YAML configuration template generator."""

from __future__ import annotations


def generate_ancilis_yaml(agent_name: str, overlay: str) -> str:
    """Return an ancilis.yaml string for the given agent name and overlay."""
    return (
        "# Ancilis configuration — generated by ancilis init\n"
        "# Docs: https://docs.ancilis.dev/configuration\n"
        "\n"
        "agent:\n"
        f"  name: {agent_name}          # Your agent's unique identifier\n"
        '  description: ""              # What this agent does\n'
        "\n"
        "security:\n"
        "  mode: audit                  # audit = observe only, enforce = block violations\n"
        "\n"
        "compliance:\n"
        "  overlays:\n"
        f"    - {overlay}                # Compliance framework to evaluate against\n"
        "\n"
        "platform:\n"
        "  url: null                    # Platform URL for future sync commands\n"
        "  api_key_env: ANCILIS_API_KEY # Env var containing the platform API key\n"
        "\n"
        "sync:\n"
        "  offline_mode: auto           # auto | always_offline | always_online\n"
        "  interval_seconds: 300\n"
        "  max_retries: 8\n"
        "  backoff_base_seconds: 2\n"
        "  max_queue_size: 10000\n"
        "  batch_size: 100              # Platform batch endpoint cap\n"
        "\n"
        "# cli:\n"
        "#   update_check: true\n"
    )
