"""Sample first-value scripts generated by ``ancilis init``."""

from __future__ import annotations

_FRAMEWORK_NOTES: dict[str, str] = {
    "langchain": "LangChain",
    "crewai": "CrewAI",
    "autogen": "AutoGen",
    "openai": "OpenAI",
    "generic": "custom Python",
}

_SCRIPT_TEMPLATE = '''\
"""First Ancilis evidence run for a {framework_label} agent.

Run:
    python ancilis_scan.py
    ancilis status --config ancilis.yaml
    ancilis scan --config ancilis.yaml
"""

from ancilis import ToolActionProducer, load_config
from ancilis.engine import Engine
from ancilis.evidence.store import EvidenceStore


config = load_config("ancilis.yaml")
evidence = EvidenceStore(config)
engine = Engine(config, evidence_store=evidence)
producer = ToolActionProducer(config=config, engine=engine, evidence_store=evidence)


def search_docs(query: str) -> dict[str, list[str]]:
    return {{"results": ["SOC 2 controls", "agent evidence", "runtime policy"]}}


def send_reply(message: str) -> str:
    return f"Sent: {{message}}"


search_docs = producer.wrap_tool(search_docs, tool_name="search_docs")
send_reply = producer.wrap_tool(send_reply, tool_name="send_reply")

print(f"Agent: {{config.agent_name}}")
print(f"Mode: {{config.mode}}")
print()

docs = search_docs("How do we prove our agent followed policy?")
print(f"search_docs -> {{docs}}")

reply = send_reply("Ancilis recorded this tool call as local evidence.")
print(f"send_reply -> {{reply}}")

summary = evidence.get_summary(session_id=producer.session_id)
chain_status = "intact" if summary["chain_valid"] else "BROKEN"
print(f"\\nEvidence: {{summary['total_evaluations']}} records this run, chain {{chain_status}}")
print("\\nNext:")
print("  ancilis status --config ancilis.yaml")
print("  ancilis scan --config ancilis.yaml")

evidence.close()
'''


def get_scan_script(framework: str) -> str:
    """Return a runnable first-value script for the detected framework."""
    framework_label = _FRAMEWORK_NOTES.get(framework, _FRAMEWORK_NOTES["generic"])
    return _SCRIPT_TEMPLATE.format(framework_label=framework_label)
